
{'date': 'Fri Dec 04 2020 17:10:14.552 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 6
    desafio_2().inicia()
TypeError: 'module' object is not callable
'''},
{'date': 'Fri Dec 04 2020 17:11:47.816 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 17
    mari().chamaa()
  module <module> line 11
    desafio_2.inicia()
AttributeError: 'module' object has no attribute 'inicia'
'''},
{'date': 'Fri Dec 04 2020 17:11:55.85 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 17
    mari().chamaa()
  module <module> line 11
    desafio_2().inicia()
TypeError: 'module' object is not callable
'''},
{'date': 'Fri Dec 04 2020 17:12:04.721 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 17
    mari().chamaa()
  module <module> line 11
    desafio_2().inicia()
TypeError: 'module' object is not callable
'''},
{'date': 'Fri Dec 04 2020 17:13:34.953 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 17
    mari().chamaa()
  module <module> line 11
    desafio_2().inicia()
TypeError: 'module' object is not callable
'''},
{'date': 'Fri Dec 11 2020 16:57:17.309 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''
 module <string> line 29
  self.Seta2 = Elemento(botao_seta2, tit="CLIQUE",
                                                                                                                                                                                                                                                                 ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Dec 18 2020 15:40:07.56 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    from roxanne.main import nome_personagem
  module roxanne.main line 15
    from stacy.main import Modulo1
  module stacy.main line 2
    from roxanne.main import nome_personagem
ImportError: cannot import name 'nome_personagem'

ImportError
Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 268
    action()
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    from roxanne.main import nome_personagem
  module roxanne.main line 15
    from stacy.main import Modulo1
  module stacy.main line 2
    from roxanne.main import nome_personagem
'''},
{'date': 'Fri Dec 18 2020 16:16:36.875 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''
 module <string> line 27
  def clique_computador (self,event = None):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Fri Dec 18 2020 16:16:49.476 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''
 module <string> line 36
  def mari(self):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Fri Dec 18 2020 16:16:55.652 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''
 module <string> line 40
  def mari2(self,*_):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Fri Dec 18 2020 16:17:08.744 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 46
    Modulo1().mari()
  module <module> line 37
    print(f'Testando {nome_personagem}')
  module <module> line 1
    (nome_personagem)
NameError: name 'nome_personagem' is not defined
'''},
{'date': 'Fri Dec 18 2020 18:39:22.752 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    from roxanne.main import Registro
  module roxanne.main line 15
    from stacy.main import Modulo1
  module stacy.main line 2
    from roxanne.main import Registro
ImportError: cannot import name 'Registro'

ImportError
Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 268
    action()
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    from roxanne.main import Registro
  module roxanne.main line 15
    from stacy.main import Modulo1
  module stacy.main line 2
    from roxanne.main import Registro
'''},
{'date': 'Fri Dec 18 2020 18:39:31.291 GMt-0300 (Brasilia Standard Time) -X- SuPyGirls -X-',
'error': '''
Exception: obj is null
  module '$exec_1850' line 2
from roxanne.main import *
'''},